# Generated by Django 5.0.6 on 2024-06-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oee_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionlog',
            name='product_total',
            field=models.IntegerField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
